config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  devise_for :users, controllers: { sessions: "devise/sessions",
                                    omniauth_callbacks: "omniauth_callbacks" }
  scope "(:locale)", locale: /en|vi/ do
    namespace :admin do
      root "adminpages#home"
      resources :users, only: %i(index destroy)
      resources :publishers
      resources :books, only: %i(index new create destroy)
      resources :categories do
        resources :books, except: %i(new create)
      end
      resources :authors
      resources :borrowings, only: %i(index update destroy)
    end
    resources :books, only: %i(index show) do
      resources :comments, only: %i(create destroy)
      resources :ratings, only: :create
    end
    resources :borrow_items, only: %i(create index destroy)
    resources :borrowings, only: %i(index create)
    resources :publishers, only: :show do
      resources :books, only: :index
    end

    root "homepages#home"
    get "/search", to: "search#index"
  end
end

app/models/book.rb
class Book < ApplicationRecord
  BOOK_PARAMS = [:name,
    :description,
    :quantity,
    :category_id,
    :publisher_id,
    :author_id,
    images_attributes: Image::IMAGE_PARAMS].freeze

  acts_as_paranoid

  belongs_to :category, optional: true
  belongs_to :publisher, optional: true
  belongs_to :author, optional: true
  has_many :book_details, dependent: :destroy
  has_many :images, dependent: :destroy
  has_many :borrow_items, dependent: :destroy
  has_many :borrowings, through: :borrow_items
  has_many :comments, dependent: :destroy
  has_many :ratings, dependent: :destroy

  accepts_nested_attributes_for :images, reject_if: :all_blank,
    allow_destroy: true

  validates :name, presence: true,
    length: {maximum: Settings.category.length}
  validates :description, presence: true,
    length: {maximum: Settings.book.description.length}
  validates :quantity, presence: true,
    numericality:
    {less_than_or_equal_to: Settings.book.quantity.length, only_integer: true}
  validates :quantity_borrowed, numericality: {only_integer: true},
    allow_nil: true

  delegate :title, to: :category, prefix: true, allow_nil: true
  delegate :name, to: :author, prefix: true, allow_nil: true
  delegate :name, to: :publisher, prefix: true, allow_nil: true

  scope :by_ids, ->(ids){where id: ids}
  scope :search_by_name, (lambda do |name|
    where "name LIKE ?", "%#{name}%" if name.present?
  end)
  scope :filter_by_publisher, (lambda do |publisher_id|
    where publisher_id: publisher_id if publisher_id.present?
  end)
end

app/controllers/admin/books_controller.rb
class Admin::BooksController < Admin::BaseController
  def new
    @book = Book.new
  end

  def index
    @books = Book.page(params[:page]).per Settings.panigate.category
  end

  def create
    @book = Book.new book_params
    if @book.save
      @book.update quantity_borrowed: @book.quantity
      flash[:success] = t "categories.message.sucsses"
      redirect_to admin_books_path
    else
      flash.now[:alert] = t "categories.message.failer"
      render :new
    end
  end

  private

  def book_params
    params.require(:book).permit Book::BOOK_PARAMS
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    params[:id] = nil if Book.pluck(:publisher_id).exclude?(params[:id].to_i)
    @books_to_publisher = Book.filter_by_publisher params[:id]
    @books = @books_to_publisher.page(params[:page])
                                .per Settings.panigate.book
    @categories = Category.all
    @authors = Author.all
  end

  def show
    @book = Book.find params[:id]
    @categories = Category.all
    @authors = Author.all
    @borrow_item = @book.borrow_items.build
    @comment = Comment.new
    @comments = @book.comments
    @rating = Rating.new
  end
end

app/views/admin/books/_book.html.erb
<tr>
  <td>
    <%= page_index params[:page], book_counter,
      Settings.panigate.category %>
  </td>
  <td><%= book.name %></td>
  <td><%= book.quantity %></td>
  <td><%= book.quantity_borrowed %></td>
  <td>
    <%= link_to "#", data: { toggle: "modal", target: "#book-#{book.id}" } do %>
      <span class="badge rounded-pill bg-info text-dark">
        <i class="fas fa-eye"></i>
      </span>
    <% end %>
    <%= link_to "#" do %>
      <span class="badge rounded-pill bg-success">
        <i class="fas fa-edit"></i>
      </span>
    <% end %>
    <%= link_to "#" do %>
      <span class="badge rounded-pill bg-danger">
        <i class="fas fa-trash-alt"></i>
      </span>
    <% end %>
    <%= render "book_detail", book: book %>
  </td>
</tr>

app/views/admin/books/_book_detail.html.erb
<div class="modal fade" id="book-<%= book.id %>">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title"><%= t ".title" %></h4>
        <button type="button" class="close" data-dismiss="modal">
          &times;
        </button>
      </div>
      <div class="modal-body">
        <div class="list_imgae_book">
          <div class="row">
            <div class="col-md-6">
              <%= render collection: book.images,
              partial: "image" %>
            </div>
            <div class="col-md-6">
              <ul>
                <li>
                  <span><%= t ".author" %>:</span>
                  <%= book.author_name %>
                </li>
                <li>
                  <span><%= t ".publisher" %>:</span>
                  <%= book.publisher_name %>
                </li>
                <li>
                  <span><%= t ".category" %>:</span>
                  <%= book.category_title %>
                </li>
              </ul>
            </div>
          </div>
        <div>
      </div>
    </div>
  </div>
</div>

app/views/admin/books/_image.html.erb
<div class="col-md-3">
  <div class="image_item">
    <%= image_tag image&.link_url %>
  </div>
</div>

app/views/admin/books/_image_fields.html.erb
<div class="nested-fields">
  <%= f.file_field :link, class: "link_count" %>
  <%= link_to_remove_association t(".removeImage"), f %>
</div>

app/views/admin/books/_list_images.html.erb
<div class="col-md-3">
  <div class="image_item">
    <%= image_tag image.link_url, style: "width: 40px" %>
  </div>
</div>

app/views/admin/books/index.html.erb
<div class="content-header">
  <div class="container-fluid">
    <div class="row mb-2">
      <div class="col-sm-6">
        <h1 class="m-0 text-dark"><%= t "books.array"%></h1>
      </div>
    </div>
  </div>
</div>
<section class="content">
  <div class="container-fluid">
    <div class="row">
      <div class="col-lg-12">
        <div class="card">
          <div class="card-body">
          <%= link_to t("books.index"), new_admin_book_path, class: "btn btn-primary" %>
            <div class="container">
              <table id="book" class="table table-striped table-bordered">
                <thead>
                  <th><%= t "books.list.column_id" %></th>
                  <th><%= t "books.list.column_name" %></th>
                  <th><%= t "books.list.column_quantity" %></th>
                  <th><%= t "books.list.column_quantity_last" %></th>
                  <th><%= t "books.list.column_action" %></th>
                </thead>
                <tbody>
                  <%= render @books %>
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/admin/books/new.html.erb
<div class="content-header">
  <div class="container-fluid">
    <div class="row mb-2">
      <div class="col-sm-6">
        <h1 class="m-0 text-dark"><%= t "books.index"%></h1>
      </div>
    </div>
  </div>
</div>
<section class="content">
  <div class="container-fluid">
    <div class="row">
      <div class="col-lg-12">
        <div class="card">
          <div class="card-body">
            <%= form_for [:admin, @book] do |f| %>
              <div class="row">
                <div class="col-md-6">
                  <div class= "valueColumn">
                    <div class="form-group">
                      <%= render "shared/error_message", object: f.object %>
                      <%= f.label :name, t(".name") %>
                      <%= f.text_field :name, class:"form-control" ,
                        placeholder: t("books.new.name") %>
                    </div>
                    <div class="form-group">
                      <%= f.label :description, t(".des") %>
                      <%= f.text_area :description, class:"form-control",
                        placeholder: t("books.new..descripton") %>
                    </div>
                    <div class="form-group">
                      <%= f.label :quantity, t(".quan") %>
                      <%= f.number_field :quantity, class:"form-control",
                        in: 1..99, step:1, placeholder: t("books.new.quantity") %>
                    </div>
                  </div>
                </div>
                <div class="col-md-6">
                  <div class="forenkey">
                    <div class="form-group">
                      <%= f.label :category_id, t(".category") %>
                      <%= f.select :category_id,
                        Category.all.pluck(:title, :id), {},
                        class:"custom-select" %>
                    </div>
                    <div class="form-group">
                      <%= f.label :publisher_id, t(".publisher") %>
                      <%= f.select :publisher_id,
                        Publisher.all.pluck(:name, :id), {},
                        class:"custom-select" %>
                    </div>
                    <div class="form-group">
                      <%= f.label :author_id, t(".author") %>
                      <%= f.select :author_id,
                        Author.all.pluck(:name, :id), {},
                        class:"custom-select" %>
                    </div>
                    <div class="form-group">
                    </div>
                    <div class="form-group">
                      <%= f.fields_for :images do |image| %>
                         <%= render "image_fields", f: image %>
                      <% end %>
                      <div class="link">
                        <%= link_to_add_association t(".addImage"), f, :images %>
                      </div>
                    </div>
                    <%= f.submit t("books.new.submit"), class: "btn btn-primary"%>
                  </div>
                </div>
              </div>
            <% end %>
        </div>
      </div>
    </div>
  </div>
</section>