config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  devise_for :users, controllers: { sessions: "devise/sessions",
                                    omniauth_callbacks: "omniauth_callbacks" }
  scope "(:locale)", locale: /en|vi/ do
    namespace :admin do
      root "adminpages#home"
      resources :users, only: %i(index destroy)
      resources :publishers
      resources :books, only: %i(index new create destroy)
      resources :categories do
        resources :books, except: %i(new create)
      end
      resources :authors
      resources :borrowings, only: %i(index update destroy)
    end
    resources :books, only: %i(index show) do
      resources :comments, only: %i(create destroy)
      resources :ratings, only: :create
    end
    resources :borrow_items, only: %i(create index destroy)
    resources :borrowings, only: %i(index create)
    resources :publishers, only: :show do
      resources :books, only: :index
    end

    root "homepages#home"
    get "/search", to: "search#index"
  end
end

app/views/layouts/admin/_footer.html.erb
<footer class="main-footer">
  <strong>Copyright © 2019 Your Stuff.</strong>
  All rights reserved.
</footer>

app/views/layouts/admin/_header.html.erb
<nav class="main-header navbar navbar-expand
    navbar-white navbar-light border-bottom">
  <ul class="navbar-nav">
    <li class="nav-item">
      <a class="nav-link" data-widget="pushmenu" href="#">
        <i class="fas fa-bars"></i>
      </a>
    </li>
    <li class="nav-item d-none d-sm-inline-block">
      <%= link_to t(".home"), admin_root_path, class: "nav-link" %>
    </li>
    <li class="nav-item d-none d-sm-inline-block">
      <%= link_to t(".contact"), "#", class: "nav-link" %>
    </li>
  </ul>
  <form class="form-inline ml-3">
    <div class="input-group input-group-sm">
      <input
        class="form-control form-control-navbar"
        type="search"
        placeholder="Search"
        aria-label="Search"/>
      <div class="input-group-append">
        <button class="btn btn-navbar" type="submit">
          <i class="fas fa-search"></i>
        </button>
      </div>
    </div>
  </form>
  <ul class="navbar-nav ml-auto">
    <li class="nav-item dropdown">
      <a class="nav-link" data-toggle="dropdown" href="#">
        <i class="far fa-comments"></i>
        <span class="badge badge-danger navbar-badge"></span>
      </a>
      <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
        <a href="#" class="dropdown-item">
          <div class="media">
            <%= image_tag Settings.image.link_1, class:"img-size-50 mr-3 img-circle"%>
            <div class="media-body">
              <h3 class="dropdown-item-title">
                <span class="float-right text-sm text-danger">
                  <i class="fas fa-star"></i>
                </span>
              </h3>
              <p class="text-sm"></p>
              <p class="text-sm text-muted">
                <i class="far fa-clock mr-1"></i>
              </p>
            </div>
          </div>
        </a>
        <div class="dropdown-divider"></div>
        <%= link_to "#", class:"dropdown-item" do %>
          <div class="media">
            <%= image_tag Settings.image.link_1, class:"img-size-50 mr-3 img-circle"%>
            <div class="media-body">
              <h3 class="dropdown-item-title">
                <span class="float-right text-sm text-muted">
                  <i class="fas fa-star"></i>
                </span>
              </h3>
              <p class="text-sm"></p>
              <p class="text-sm text-muted">
                <i class="far fa-clock mr-1"></i>
              </p>
            </div>
          </div>
        <% end %>
        <div class="dropdown-divider"></div>
        <%= link_to "#", class: "dropdown-item" do %>
          <!-- Message Start -->
          <div class="media">
            <%= image_tag Settings.image.link_1, class:"img-size-50 mr-3 img-circle"%>
            <div class="media-body">
              <h3 class="dropdown-item-title">
                <span class="float-right text-sm text-warning">
                  <i class="fas fa-star"></i>
                </span>
              </h3>
              <p class="text-sm"></p>
              <p class="text-sm text-muted">
                <i class="far fa-clock mr-1"></i>
              </p>
            </div>
          </div>
        <% end %>
        <div class="dropdown-divider"></div>
        <%= link_to "", "#", class:"dropdown-item dropdown-footer"%>
      </div>
    </li>
    <!-- Notifications Dropdown Menu -->
    <li class="nav-item dropdown">
      <%= link_to "#", class: "nav-link", data: { toggle: "dropdown"} do %>
        <i class="far fa-bell"></i>
        <span class="badge badge-warning navbar-badge"></span>
      <% end %>
      <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
        <span class="dropdown-item dropdown-header"></span>
        <div class="dropdown-divider"></div>
        <%= link_to "#" , class: "dropdown-item" do %>
          <i class="fas fa-envelope mr-2"></i>
          <span class="float-right text-muted text-sm"></span>
        <% end %>
        <div class="dropdown-divider"></div>
        <%= link_to "#" , class: "dropdown-item" do %>
          <i class="fas fa-envelope mr-2"></i>
          <span class="float-right text-muted text-sm"></span>
        <% end %>
        <div class="dropdown-divider"></div>
        <%= link_to "#" , class: "dropdown-item" do %>
          <i class="fas fa-envelope mr-2"></i>
          <span class="float-right text-muted text-sm"></span>
        <% end %>
        <div class="dropdown-divider"></div>
        <%= link_to "", "#", class: "dropdown-item dropdown-footer" %>
      </div>
    </li>
  </ul>
</nav>

app/views/layouts/admin/_sidebar.html.erb
<aside class="main-sidebar sidebar-dark-primary elevation-4">
    <!-- Brand Logo -->
  <%= link_to admin_root_path, class: "brand-link" do %>
    <span class="brand-text font-weight-light"><%= t ".logo"%></span>
  <% end %>
<!-- Sidebar -->
  <div class="slimScrollDiv" style="position: relative; overflow: hidden; width: auto; height: 652px;">
  <div class="sidebar" style="min-height: 652px; overflow: hidden; width: auto; height: 652px;">
    <!-- Sidebar user panel (optional) -->
    <div class="user-panel mt-3 pb-3 mb-3 d-flex">
      <div class="image">
        <%= image_tag "logo.jpg", class: "img-circle elevation-2", alt:"Logo" %>
      </div>
      <div class="info">
        <%= link_to t(".actor"), admin_root_path, class: "d-block" %>
      </div>
    </div>
    <nav class="mt-2">
      <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
        <li class="nav-item has-treeview menu-open">
          <a href="#" class="nav-link active">
            <i class="nav-icon fas fa-tachometer-alt"></i>
            <p>
              <%= t ".list"%>
              <i class="right fas fa-angle-left"></i>
            </p>
          </a>
          <ul class="nav nav-treeview">
            <li class="nav-item">
              <%= link_to admin_books_path, class: "nav-link active" do %>
                <i class="far fa-circle nav-icon"></i>
                <p><%= t ".book"%></p>
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to admin_authors_path, class: "nav-link " do %>
                <i class="far fa-circle nav-icon"></i>
                <p><%= t ".author"%></p>
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to admin_categories_path, class: "nav-link " do %>
                <i class="far fa-circle nav-icon"></i>
                <p><%= t ".category"%></p>
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to admin_publishers_path, class: "nav-link " do %>
                <i class="far fa-circle nav-icon"></i>
                <p><%= t ".publisher"%></p>
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to admin_borrowings_path, class: "nav-link " do %>
                <i class="nav-icon fas fa-th"></i>
                <p><%= t ".borrowing" %></p>
                 <span class="right badge badge-danger"><%= t ".new" %></span>
              <% end %>
            </li>
          </ul>
        </li>
      </ul>
    </nav>
  </div>
</aside>

app/views/layouts/admin/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Admin</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", media: "all",
      "data-turbolinks-track": "reload" %>
    <%= javascript_pack_tag "application",
      "data-turbolinks-track": "reload" %>
  </head>
  <body class="sidebar-mini">
    <div class="wrapper">
      <%= render "layouts/admin/header" %>
      <%= render "layouts/admin/sidebar" %>
      <div class="content-wrapper">
        <%= yield %>
        <%= toastr_flash %>
      </div>
      <%= render "layouts/admin/footer" %>
    </div>
  </body>
</html>