config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  devise_for :users, controllers: { sessions: "devise/sessions",
                                    omniauth_callbacks: "omniauth_callbacks" }
  scope "(:locale)", locale: /en|vi/ do
    namespace :admin do
      root "adminpages#home"
      resources :users, only: %i(index destroy)
      resources :publishers
      resources :books, only: %i(index new create destroy)
      resources :categories do
        resources :books, except: %i(new create)
      end
      resources :authors
      resources :borrowings, only: %i(index update destroy)
    end
    resources :books, only: %i(index show) do
      resources :comments, only: %i(create destroy)
      resources :ratings, only: :create
    end
    resources :borrow_items, only: %i(create index destroy)
    resources :borrowings, only: %i(index create)
    resources :publishers, only: :show do
      resources :books, only: :index
    end

    root "homepages#home"
    get "/search", to: "search#index"
  end
end

app/views/shared/_borrow_item.html.erb
<% if book.quantity_borrowed != Settings.quantity %>
  <a data-id="<%= book.id %>" class="cart btn-add-to-cart2">
    <i class="fas fa-shopping-bag"></i>
  </a>
<% else %>
  <%= link_to t("share.sold"), "#", class: "cart", id:"borrow_book" %>
<% end %>

app/views/shared/_error_message.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      <%= t "shared.error.title" %>
      <%= pluralize object.errors.size, t("shared.error.name") %>.
    </div>
    <ul>
      <% object.errors.full_messages.each do |msg| %>
        <li> <%= msg %> </li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_list_book.html.erb
<% @books.each do |book|%>
  <div class="product product__style--3">
    <div class="col-lg-3 col-md-3 col-sm-6 col-12">
      <div class="product__thumb">
        <%= link_to book_path(book), class:"first__img" do %>
          <%= image_tag book.images.first.link.to_s %>
        <% end %>
        <%= link_to book_path(book), class:"second__img animation1" do %>
          <%= image_tag book.category.avatar %>
        <% end %>
        <div class="hot__box">
          <span class="hot-label"><%= t ".hot" %></span>
        </div>
      </div>
      <div class="product__content content--center">
        <h4><a href="single-product.html"><%= book.name %></a></h4>
        <ul class="prize d-flex">
          <li></li>
        </ul>
        <div class="action">
          <div class="actions_inner">
            <ul class="add_to_links">
              <li><a class="cart" href="cart.html"><i class="fas fa-shopping-bag"></i></a></li>
              <li>
                <a data-toggle="modal" class="quickview modal-view detail-link" href="#productmodal">
                  <i class="fas fa-search"></i>
                </a>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/shared/_quiky_view.html.erb
<div id="quickview-wrapper">
  <div class="modal fade" id="book-<%= book.id %>" tabindex="-1" role="dialog">
    <div class="modal-dialog modal__container" role="document">
      <div class="modal-content">
        <div class="modal-header modal__header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <div class="modal-product">
            <div class="product-images">
              <div class="main-image images">
                <%= image_tag book.images.first.link_url if book.images.present? %>
              </div>
            </div>
            <div class="product-info">
              <h1><%= book.name %></h1>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>